project:
  type: website
  output-dir: docs

website:
  title: "Max Hickman"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Mini-Project1.qmd
      - Map.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

